/**
 * Build the docs search index D1 serves, from `.guren/docs.gen.ts`. Writes two
 * uncommitted files: `.guren/search-index.sql` (applied to D1 by the deploy
 * workflow) and `.guren/search-index.gen.ts` (table names, bundled into the
 * Worker by wrangler at deploy time). Runs after the docs prerender and before
 * `wrangler deploy`; never into `.cloudflare/`, which `buildCloudflareOutput()`
 * deletes wholesale. Every build names its own tables: a contentless FTS5 table
 * cannot be emptied (`DELETE` fails) and D1 has no transactions to make a
 * rename atomic against a serving Worker. `--stub` writes an empty module if none exists.
 */
import { closeSync, mkdirSync, openSync, statSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  collectRows,
  computeBuildId,
  renderIndexSql,
  searchTableName,
  sectionsTableName,
  type DocsByLocale,
} from '../app/Services/search-index-build.js'

const webRoot = fileURLToPath(new URL('..', import.meta.url))
const outDir = resolve(webRoot, '.guren')
const sqlPath = resolve(outDir, 'search-index.sql')
const genPath = resolve(outDir, 'search-index.gen.ts')

const HEADER = '// Generated by web/scripts/build-search-index.ts — do not edit.\n'

const MODULE_TYPES = `
export interface SearchIndexBuild {
  /** False in a checkout that has not run the real build. */
  indexed: boolean
  /** Hash of the indexed corpus; also the suffix both table names carry. */
  buildId: string
  sectionsTable: string
  searchTable: string
}
`

function renderModule(build: {
  indexed: boolean
  buildId: string
  sectionsTable: string
  searchTable: string
}): string {
  return `${HEADER}${MODULE_TYPES}
export const searchIndexBuild: SearchIndexBuild = ${JSON.stringify(build, null, 2)}
`
}

/**
 * Claim the file with `wx` rather than testing for it first: this runs from
 * `prerender:stub`, which several scripts invoke concurrently, and a real
 * build's output must never be replaced by a stub that a check-then-write
 * raced into.
 */
function writeStub(): void {
  mkdirSync(outDir, { recursive: true })

  let handle: number
  try {
    handle = openSync(genPath, 'wx')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'EEXIST') {
      return
    }
    throw error
  }

  try {
    writeFileSync(
      handle,
      renderModule({ indexed: false, buildId: '', sectionsTable: '', searchTable: '' }),
      'utf8',
    )
  } finally {
    closeSync(handle)
  }
  console.log('  web/.guren/search-index.gen.ts — stub')
}

async function build(): Promise<void> {
  mkdirSync(outDir, { recursive: true })

  const { docsData } = await import('../.guren/docs.gen.js')
  if (!docsData.prerendered) {
    throw new Error('Docs are not prerendered — run `bun run prerender` first.')
  }

  const rows = collectRows(docsData.docs as DocsByLocale)
  if (rows.length === 0) {
    throw new Error('No sections were extracted — the rendered docs carry no headings.')
  }

  const buildId = computeBuildId(rows)
  const sql = renderIndexSql(rows, buildId)

  writeFileSync(sqlPath, sql, 'utf8')
  writeFileSync(
    genPath,
    renderModule({
      indexed: true,
      buildId,
      sectionsTable: sectionsTableName(buildId),
      searchTable: searchTableName(buildId),
    }),
    'utf8',
  )

  const largest = Math.max(
    ...sql.split(/;\n/u).map((statement) => Buffer.byteLength(statement, 'utf8')),
  )
  console.log(`Search index ${buildId}: ${rows.length} sections`)
  console.log(
    `  web/.guren/search-index.sql — ${(statSync(sqlPath).size / 1024).toFixed(1)} KB, ` +
      `largest statement ${(largest / 1024).toFixed(1)} KB`,
  )
  console.log('  web/.guren/search-index.gen.ts')
}

if (process.argv.includes('--stub')) {
  writeStub()
} else {
  await build()
}
