/**
 * Build the docs search index that D1 serves.
 *
 * Reads the docs already rendered into `.guren/docs.gen.ts` and writes two
 * files, neither of them committed:
 *
 *   .guren/search-index.sql     — applied to D1 by the deploy workflow
 *   .guren/search-index.gen.ts  — the table names, baked into the Worker
 *
 * Ordering matters, and it is possible to get wrong in both directions. The
 * generated module has to exist *before* `vite build`, or the bundle ships
 * without the table names it needs; the SQL has to be applied *before*
 * `wrangler deploy`, or the deployed Worker names tables nobody created. And
 * nothing goes in `.cloudflare/` — `buildCloudflareOutput()` deletes that
 * directory wholesale (packages/plugin-cloudflare/src/build.ts).
 *
 *   bun run prerender
 *   bun scripts/build-search-index.ts
 *   bun run build && bun scripts/cloudflare-build.ts
 *   wrangler d1 execute … --file=.guren/search-index.sql   # if the id moved
 *   wrangler deploy
 *
 * Every build names its own tables and the deploy is what switches between
 * them. Two reasons it has to work that way: a contentless FTS5 table cannot
 * be emptied (`DELETE` fails outright), and D1 has no explicit transactions,
 * so there is no moment at which a rename could be made atomic against a
 * Worker that is still serving.
 *
 * Usage:
 *   bun scripts/build-search-index.ts          # real build
 *   bun scripts/build-search-index.ts --stub   # write an empty generated
 *                                              # module if none exists, so
 *                                              # tsc/dev/test resolve it
 */
import { existsSync, mkdirSync, statSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  collectRows,
  computeBuildId,
  renderIndexSql,
  searchTableName,
  sectionsTableName,
  type DocsByLocale,
} from '../app/Services/search-index-build.js'

const webRoot = fileURLToPath(new URL('..', import.meta.url))
const outDir = resolve(webRoot, '.guren')
const sqlPath = resolve(outDir, 'search-index.sql')
const genPath = resolve(outDir, 'search-index.gen.ts')

const HEADER = '// Generated by web/scripts/build-search-index.ts — do not edit.\n'

const MODULE_TYPES = `
export interface SearchIndexBuild {
  /** False in a checkout that has not run the real build. */
  indexed: boolean
  /** Hash of the indexed corpus; also the suffix both table names carry. */
  buildId: string
  sectionsTable: string
  searchTable: string
}
`

function renderModule(build: {
  indexed: boolean
  buildId: string
  sectionsTable: string
  searchTable: string
}): string {
  return `${HEADER}${MODULE_TYPES}
export const searchIndexBuild: SearchIndexBuild = ${JSON.stringify(build, null, 2)}
`
}

function writeStub(): void {
  mkdirSync(outDir, { recursive: true })
  if (existsSync(genPath)) {
    return
  }
  writeFileSync(
    genPath,
    renderModule({ indexed: false, buildId: '', sectionsTable: '', searchTable: '' }),
    'utf8',
  )
  console.log('  web/.guren/search-index.gen.ts — stub')
}

async function build(): Promise<void> {
  mkdirSync(outDir, { recursive: true })

  const { docsData } = await import('../.guren/docs.gen.js')
  if (!docsData.prerendered) {
    throw new Error('Docs are not prerendered — run `bun run prerender` first.')
  }

  const rows = collectRows(docsData.docs as DocsByLocale)
  if (rows.length === 0) {
    throw new Error('No sections were extracted — the rendered docs carry no headings.')
  }

  const buildId = computeBuildId(rows)
  const sql = renderIndexSql(rows, buildId)

  writeFileSync(sqlPath, sql, 'utf8')
  writeFileSync(
    genPath,
    renderModule({
      indexed: true,
      buildId,
      sectionsTable: sectionsTableName(buildId),
      searchTable: searchTableName(buildId),
    }),
    'utf8',
  )

  const largest = Math.max(
    ...sql.split(/;\n/u).map((statement) => Buffer.byteLength(statement, 'utf8')),
  )
  console.log(`Search index ${buildId}: ${rows.length} sections`)
  console.log(
    `  web/.guren/search-index.sql — ${(statSync(sqlPath).size / 1024).toFixed(1)} KB, ` +
      `largest statement ${(largest / 1024).toFixed(1)} KB`,
  )
  console.log('  web/.guren/search-index.gen.ts')
}

if (process.argv.includes('--stub')) {
  writeStub()
} else {
  await build()
}
