/**
 * Prerender docs and landing-page code samples into static TypeScript modules
 * under web/.guren/, so production request paths need no shiki/marked/node:fs.
 *
 *   bun scripts/prerender-docs.ts          # full render (build time)
 *   bun scripts/prerender-docs.ts --stub   # empty stubs only when missing, so
 *                                          # dev/test/tsc resolve the imports
 */
import { existsSync, mkdirSync, statSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { gzipSync } from 'node:zlib'

const webRoot = fileURLToPath(new URL('..', import.meta.url))
const outDir = resolve(webRoot, '.guren')
const docsGenPath = resolve(outDir, 'docs.gen.ts')
const homeSamplesGenPath = resolve(outDir, 'home-samples.gen.ts')

const HEADER = '// Generated by web/scripts/prerender-docs.ts — do not edit.\n'

const DOCS_MODULE_TYPES = `
export interface PrerenderedDoc {
  title: string
  description?: string
  raw: string
  html: string
}

export interface PrerenderedDocsData {
  prerendered: boolean
  docs: Record<string, Record<string, Record<string, PrerenderedDoc>>>
}
`

const HOME_MODULE_TYPES = `
export interface PrerenderedHomeSamples {
  prerendered: boolean
  samples: Record<string, string>
}
`

interface PrerenderedDoc {
  title: string
  description?: string
  raw: string
  html: string
}

function renderDocsModule(data: {
  prerendered: boolean
  docs: Record<string, Record<string, Record<string, PrerenderedDoc>>>
}): string {
  // Double-stringify: embedding one large JSON string parses faster than a
  // giant object literal and keeps tsc from type-inferring megabytes of AST.
  return `${HEADER}${DOCS_MODULE_TYPES}
export const docsData: PrerenderedDocsData = JSON.parse(${JSON.stringify(JSON.stringify(data))})
`
}

function renderHomeSamplesModule(data: {
  prerendered: boolean
  samples: Record<string, string>
}): string {
  return `${HEADER}${HOME_MODULE_TYPES}
export const homeSamples: PrerenderedHomeSamples = JSON.parse(${JSON.stringify(JSON.stringify(data))})
`
}

function writeModule(path: string, content: string): void {
  writeFileSync(path, content, 'utf8')
  const rawBytes = statSync(path).size
  const gzippedBytes = gzipSync(Buffer.from(content, 'utf8')).length
  console.log(`  ${path.replace(webRoot, 'web/')} — ${formatBytes(rawBytes)} raw, ${formatBytes(gzippedBytes)} gzipped`)
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) {
    return `${bytes} B`
  }
  return `${(bytes / 1024).toFixed(1)} KB`
}

function writeStubs(): void {
  mkdirSync(outDir, { recursive: true })

  if (!existsSync(docsGenPath)) {
    writeModule(docsGenPath, renderDocsModule({ prerendered: false, docs: {} }))
  }
  if (!existsSync(homeSamplesGenPath)) {
    writeModule(homeSamplesGenPath, renderHomeSamplesModule({ prerendered: false, samples: {} }))
  }
}

async function prerender(): Promise<void> {
  mkdirSync(outDir, { recursive: true })

  const [{ FsDocsStore }, { highlightCodeExamples }, { DOC_CATEGORY_KEYS, DOC_LOCALE_KEYS }] =
    await Promise.all([
      import('../app/Services/FsDocsStore.js'),
      import('../app/Services/highlight-code-examples.js'),
      import('../app/Services/docs-config.js'),
    ])

  const store = new FsDocsStore()
  const docs: Record<string, Record<string, Record<string, PrerenderedDoc>>> = {}
  let count = 0

  // Stable alphabetical key order at every level so rebuilds don't churn.
  for (const locale of [...DOC_LOCALE_KEYS].sort()) {
    const localeBucket: Record<string, Record<string, PrerenderedDoc>> = {}

    for (const category of [...DOC_CATEGORY_KEYS].sort()) {
      const summaries = await store.list(category, locale)
      const slugs = summaries.map((doc) => doc.slug).sort()

      const rendered = await Promise.all(
        slugs.map(async (slug) => {
          const [raw, doc] = await Promise.all([
            store.getRaw(category, slug, locale),
            store.getRendered(category, slug, locale),
          ])
          if (raw === null || doc === null) {
            throw new Error(`Failed to prerender ${locale}/${category}/${slug}`)
          }
          return [slug, { title: doc.title, description: doc.description, raw, html: doc.html }] as const
        }),
      )

      localeBucket[category] = Object.fromEntries(rendered)
      count += rendered.length
    }

    docs[locale] = localeBucket
  }

  console.log(`Prerendered ${count} docs:`)
  writeModule(docsGenPath, renderDocsModule({ prerendered: true, docs }))

  const samples = await highlightCodeExamples()
  const sortedSamples = Object.fromEntries(
    Object.entries(samples).sort(([a], [b]) => a.localeCompare(b)),
  )

  console.log('Prerendered home code samples:')
  writeModule(homeSamplesGenPath, renderHomeSamplesModule({ prerendered: true, samples: sortedSamples }))
}

if (process.argv.includes('--stub')) {
  writeStubs()
} else {
  await prerender()
}
