/**
 * Prerender docs and landing-page code samples at build time, so production
 * request paths need no shiki/marked/node:fs.
 *   bun scripts/prerender-docs.ts          # full render (build time)
 *   bun scripts/prerender-docs.ts --stub   # empty stubs only when missing (dev/test/tsc)
 * The rendered docs go under public/ (a JSON fragment and a .md per doc, plus
 * llms-full.txt) for Workers Static Assets, read back via the ASSETS binding;
 * only the manifest (titles, descriptions) is a module. Bundled, 140 docs were
 * 83% of the worker and ~40 MB of every isolate's heap.
 */
import { existsSync, mkdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { gzipSync } from 'node:zlib'

import {
  docFragmentPath,
  docMarkdownPath,
  DOC_FRAGMENT_ROOT,
  LLMS_FULL_PATH,
  manifestEntry,
  type DocFragment,
  type DocManifestEntry,
  type DocsManifest,
  type DocsManifestIndex,
} from '../app/Services/docs-manifest.js'
import { docsBasePath } from '../config/site.js'

import { formatBytes } from './lib/format-bytes.js'
import { publicFile } from './lib/public-dir.js'

const webRoot = fileURLToPath(new URL('..', import.meta.url))
const outDir = resolve(webRoot, '.guren')
const manifestGenPath = resolve(outDir, 'docs-manifest.gen.ts')
const homeSamplesGenPath = resolve(outDir, 'home-samples.gen.ts')

const HEADER = '// Generated by web/scripts/prerender-docs.ts — do not edit.\n'

const HOME_MODULE_TYPES = `
export interface PrerenderedHomeSamples {
  prerendered: boolean
  samples: Record<string, string>
}
`

function renderManifestModule(manifest: DocsManifest): string {
  return `${HEADER}import type { DocsManifest } from '../app/Services/docs-manifest.js'

export const docsManifest: DocsManifest = ${JSON.stringify(manifest, null, 2)}
`
}

function renderHomeSamplesModule(data: {
  prerendered: boolean
  samples: Record<string, string>
}): string {
  // Double-stringify: embedding one large JSON string parses faster than a
  // giant object literal and keeps tsc from type-inferring the AST.
  return `${HEADER}${HOME_MODULE_TYPES}
export const homeSamples: PrerenderedHomeSamples = JSON.parse(${JSON.stringify(JSON.stringify(data))})
`
}

function writeModule(path: string, content: string): void {
  writeFileSync(path, content, 'utf8')
  const rawBytes = statSync(path).size
  const gzippedBytes = gzipSync(Buffer.from(content, 'utf8')).length
  console.log(`  ${path.replace(webRoot, 'web/')} — ${formatBytes(rawBytes)} raw, ${formatBytes(gzippedBytes)} gzipped`)
}

const createdDirs = new Set<string>()

function writePublicFile(publicPath: string, content: string): number {
  const file = publicFile(publicPath)
  const dir = dirname(file)
  if (!createdDirs.has(dir)) {
    mkdirSync(dir, { recursive: true })
    createdDirs.add(dir)
  }
  writeFileSync(file, content, 'utf8')
  return Buffer.byteLength(content, 'utf8')
}

function writeStubs(): void {
  mkdirSync(outDir, { recursive: true })

  if (!existsSync(manifestGenPath)) {
    writeModule(manifestGenPath, renderManifestModule({ prerendered: false, docs: {} }))
  }
  if (!existsSync(homeSamplesGenPath)) {
    writeModule(homeSamplesGenPath, renderHomeSamplesModule({ prerendered: false, samples: {} }))
  }
}

/**
 * Everything a previous run wrote goes first, so a doc deleted from docs/ does
 * not stay served and does not reach the next search index. The manifest is
 * what names the live set; these directories hold nothing else.
 */
function clearPublicOutput(): void {
  rmSync(publicFile(DOC_FRAGMENT_ROOT), { recursive: true, force: true })
  rmSync(publicFile(docsBasePath('en')), { recursive: true, force: true })
  rmSync(publicFile(LLMS_FULL_PATH), { force: true })
}

async function prerender(): Promise<void> {
  mkdirSync(outDir, { recursive: true })

  const [{ FsDocsStore }, { DocsService }, { buildLlmsFull }, { highlightCodeExamples }, { DOC_CATEGORY_KEYS, DOC_LOCALE_KEYS }] =
    await Promise.all([
      import('../app/Services/FsDocsStore.js'),
      import('../app/Services/DocsService.js'),
      import('../app/Services/llms-full.js'),
      import('../app/Services/highlight-code-examples.js'),
      import('../app/Services/docs-config.js'),
    ])

  const store = new FsDocsStore()
  const manifest: DocsManifestIndex = {}
  // llms-full.txt is the English sources concatenated: kept from this pass
  // rather than read from disk a second time.
  const englishRaw = new Map<string, string>()
  let count = 0
  let htmlBytes = 0
  let markdownBytes = 0

  clearPublicOutput()

  // Stable alphabetical key order at every level so rebuilds don't churn.
  for (const locale of [...DOC_LOCALE_KEYS].sort()) {
    manifest[locale] = {}

    for (const category of [...DOC_CATEGORY_KEYS].sort()) {
      const summaries = await store.list(category, locale)
      const slugs = summaries.map((doc) => doc.slug).sort()

      const rendered = await Promise.all(
        slugs.map(async (slug) => {
          const [raw, doc] = await Promise.all([
            store.getRaw(category, slug, locale),
            store.getRendered(category, slug, locale),
          ])
          if (raw === null || doc === null) {
            throw new Error(`Failed to prerender ${locale}/${category}/${slug}`)
          }
          return { slug, raw, doc }
        }),
      )

      const bucket: Record<string, DocManifestEntry> = {}
      for (const { slug, raw, doc } of rendered) {
        const fragment: DocFragment = { ...manifestEntry(doc), html: doc.html }
        htmlBytes += writePublicFile(docFragmentPath(locale, category, slug), JSON.stringify(fragment))
        markdownBytes += writePublicFile(docMarkdownPath(locale, category, slug), raw)
        bucket[slug] = manifestEntry(doc)
        if (locale === 'en') {
          englishRaw.set(`${category}/${slug}`, raw)
        }
      }

      manifest[locale][category] = bucket
      count += rendered.length
    }
  }

  console.log(`Prerendered ${count} docs:`)
  console.log(`  web/public${DOC_FRAGMENT_ROOT}/ — ${formatBytes(htmlBytes)} of rendered fragments`)
  console.log(`  web/public${docsBasePath('en')}/ — ${formatBytes(markdownBytes)} of markdown`)
  writeModule(manifestGenPath, renderManifestModule({ prerendered: true, docs: manifest }))

  const service = new DocsService(store)
  const llmsFull = await buildLlmsFull({
    listDocs: (locale) => service.listDocs(locale),
    getRawMarkdown: async (category, slug) => englishRaw.get(`${category}/${slug}`) ?? null,
  })
  console.log(`  web/public${LLMS_FULL_PATH} — ${formatBytes(writePublicFile(LLMS_FULL_PATH, llmsFull))}`)

  const samples = await highlightCodeExamples()
  const sortedSamples = Object.fromEntries(
    Object.entries(samples).sort(([a], [b]) => a.localeCompare(b)),
  )

  console.log('Prerendered home code samples:')
  writeModule(homeSamplesGenPath, renderHomeSamplesModule({ prerendered: true, samples: sortedSamples }))
}

if (process.argv.includes('--stub')) {
  writeStubs()
} else {
  await prerender()
}
