/**
 * Prerender docs and landing-page code samples at build time, so production
 * request paths need no shiki/marked/node:fs.
 *   bun scripts/prerender-docs.ts          # full render (build time)
 *   bun scripts/prerender-docs.ts --stub   # empty stubs only when missing (dev/test/tsc)
 * The rendered docs go under public/ (a JSON fragment and a .md per doc, plus
 * llms-full.txt) for Workers Static Assets, read back via the ASSETS binding;
 * only the manifest (titles, descriptions) is a module. Bundled, 140 docs were
 * 83% of the worker and ~40 MB of every isolate's heap.
 */
import { existsSync, mkdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { gzipSync } from 'node:zlib'

import {
  docFragmentPath,
  docMarkdownPath,
  DOC_FRAGMENT_ROOT,
  LLMS_FULL_PATH,
  type DocFragment,
  type DocsManifest,
  type DocsManifestIndex,
} from '../app/Services/docs-manifest.js'
import { docsBasePath } from '../config/site.js'

const webRoot = fileURLToPath(new URL('..', import.meta.url))
const outDir = resolve(webRoot, '.guren')
const publicDir = resolve(webRoot, 'public')
const manifestGenPath = resolve(outDir, 'docs-manifest.gen.ts')
const homeSamplesGenPath = resolve(outDir, 'home-samples.gen.ts')

const HEADER = '// Generated by web/scripts/prerender-docs.ts — do not edit.\n'

const MANIFEST_MODULE_TYPES = `
export interface DocManifestEntry {
  title: string
  description?: string
}

export interface DocsManifest {
  prerendered: boolean
  /** Locale, then category, then slug. The content itself lives under public/. */
  docs: Record<string, Record<string, Record<string, DocManifestEntry>>>
}
`

const HOME_MODULE_TYPES = `
export interface PrerenderedHomeSamples {
  prerendered: boolean
  samples: Record<string, string>
}
`

function renderManifestModule(manifest: DocsManifest): string {
  return `${HEADER}${MANIFEST_MODULE_TYPES}
export const docsManifest: DocsManifest = ${JSON.stringify(manifest, null, 2)}
`
}

function renderHomeSamplesModule(data: {
  prerendered: boolean
  samples: Record<string, string>
}): string {
  // Double-stringify: embedding one large JSON string parses faster than a
  // giant object literal and keeps tsc from type-inferring the AST.
  return `${HEADER}${HOME_MODULE_TYPES}
export const homeSamples: PrerenderedHomeSamples = JSON.parse(${JSON.stringify(JSON.stringify(data))})
`
}

function writeModule(path: string, content: string): void {
  writeFileSync(path, content, 'utf8')
  const rawBytes = statSync(path).size
  const gzippedBytes = gzipSync(Buffer.from(content, 'utf8')).length
  console.log(`  ${relative(path)} — ${formatBytes(rawBytes)} raw, ${formatBytes(gzippedBytes)} gzipped`)
}

function writePublicFile(publicPath: string, content: string): number {
  const file = resolve(publicDir, `.${publicPath}`)
  mkdirSync(dirname(file), { recursive: true })
  writeFileSync(file, content, 'utf8')
  return Buffer.byteLength(content, 'utf8')
}

function relative(path: string): string {
  return path.replace(webRoot, 'web/')
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) {
    return `${bytes} B`
  }
  if (bytes < 1024 * 1024) {
    return `${(bytes / 1024).toFixed(1)} KB`
  }
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function writeStubs(): void {
  mkdirSync(outDir, { recursive: true })

  if (!existsSync(manifestGenPath)) {
    writeModule(manifestGenPath, renderManifestModule({ prerendered: false, docs: {} }))
  }
  if (!existsSync(homeSamplesGenPath)) {
    writeModule(homeSamplesGenPath, renderHomeSamplesModule({ prerendered: false, samples: {} }))
  }
}

/**
 * Everything a previous run wrote goes first, so a doc deleted from docs/ does
 * not stay served and does not reach the next search index. The manifest is
 * what names the live set; these directories hold nothing else.
 */
function clearPublicOutput(): void {
  rmSync(resolve(publicDir, `.${DOC_FRAGMENT_ROOT}`), { recursive: true, force: true })
  rmSync(resolve(publicDir, `.${docsBasePath('en')}`), { recursive: true, force: true })
  rmSync(resolve(publicDir, `.${LLMS_FULL_PATH}`), { force: true })
}

async function prerender(): Promise<void> {
  // DocsService reaches the manifest module statically; on a fresh checkout it
  // does not exist yet, so the stub goes in first and is replaced below.
  writeStubs()

  const [{ FsDocsStore }, { DocsService }, { buildLlmsFull }, { highlightCodeExamples }, { DOC_CATEGORY_KEYS, DOC_LOCALE_KEYS }] =
    await Promise.all([
      import('../app/Services/FsDocsStore.js'),
      import('../app/Services/DocsService.js'),
      import('../app/Services/llms-full.js'),
      import('../app/Services/highlight-code-examples.js'),
      import('../app/Services/docs-config.js'),
    ])

  const store = new FsDocsStore()
  const manifest: DocsManifestIndex = {}
  let count = 0
  let htmlBytes = 0
  let markdownBytes = 0

  clearPublicOutput()

  // Stable alphabetical key order at every level so rebuilds don't churn.
  for (const locale of [...DOC_LOCALE_KEYS].sort()) {
    const localeBucket: DocsManifestIndex[string] = {}

    for (const category of [...DOC_CATEGORY_KEYS].sort()) {
      const summaries = await store.list(category, locale)
      const slugs = summaries.map((doc) => doc.slug).sort()

      const rendered = await Promise.all(
        slugs.map(async (slug) => {
          const [raw, doc] = await Promise.all([
            store.getRaw(category, slug, locale),
            store.getRendered(category, slug, locale),
          ])
          if (raw === null || doc === null) {
            throw new Error(`Failed to prerender ${locale}/${category}/${slug}`)
          }
          return { slug, raw, doc }
        }),
      )

      const categoryBucket: DocsManifestIndex[string][string] = {}
      for (const { slug, raw, doc } of rendered) {
        const entry = { title: doc.title, ...(doc.description !== undefined ? { description: doc.description } : {}) }
        const fragment: DocFragment = { ...entry, html: doc.html }
        htmlBytes += writePublicFile(docFragmentPath(locale, category, slug), JSON.stringify(fragment))
        markdownBytes += writePublicFile(docMarkdownPath(locale, category, slug), raw)
        categoryBucket[slug] = entry
      }

      localeBucket[category] = categoryBucket
      count += rendered.length
    }

    manifest[locale] = localeBucket
  }

  console.log(`Prerendered ${count} docs:`)
  console.log(`  web/public${DOC_FRAGMENT_ROOT}/ — ${formatBytes(htmlBytes)} of rendered fragments`)
  console.log(`  web/public${docsBasePath('en')}/ — ${formatBytes(markdownBytes)} of markdown`)
  writeModule(manifestGenPath, renderManifestModule({ prerendered: true, docs: manifest }))

  const llmsFull = await buildLlmsFull(new DocsService(store))
  console.log(`  web/public${LLMS_FULL_PATH} — ${formatBytes(writePublicFile(LLMS_FULL_PATH, llmsFull))}`)

  const samples = await highlightCodeExamples()
  const sortedSamples = Object.fromEntries(
    Object.entries(samples).sort(([a], [b]) => a.localeCompare(b)),
  )

  console.log('Prerendered home code samples:')
  writeModule(homeSamplesGenPath, renderHomeSamplesModule({ prerendered: true, samples: sortedSamples }))
}

if (process.argv.includes('--stub')) {
  writeStubs()
} else {
  await prerender()
}
