import { defineConfig } from 'tsup'

export default defineConfig([
  {
    entry: [
      'src/index.ts',
      'src/auth/index.ts',
      'src/authorization/index.ts',
      'src/broadcasting/index.ts',
      'src/cache/index.ts',
      'src/encryption/index.ts',
      'src/events/index.ts',
      'src/health/index.ts',
      'src/i18n/index.ts',
      'src/legacy-validation/index.ts',
      'src/logging/index.ts',
      'src/mail/index.ts',
      'src/notifications/index.ts',
      'src/queue/index.ts',
      'src/runtime/index.ts',
      'src/scheduling/index.ts',
      'src/storage/index.ts',
      'src/vite/index.ts',
    ],
    format: ['esm'],
    splitting: false,
    dts: true,
    outDir: 'dist',
    clean: true,
    tsconfig: 'tsconfig.json',
    external: [
      'bun:sqlite',
      'drizzle-orm/bun-sqlite',
      'drizzle-orm/bun-sqlite/migrator',
      '@aws-sdk/client-sqs',
      '@modelcontextprotocol/sdk',
      '@guren/cli',
      'zod',
    ],
  },
  // MCP + Lambda: built without DTS to avoid OOM from heavy external types
  {
    entry: ['src/mcp/index.ts', 'src/lambda/index.ts'],
    format: ['esm'],
    splitting: false,
    dts: false,
    outDir: 'dist',
    clean: false,
    tsconfig: 'tsconfig.json',
    external: [
      'bun:sqlite',
      'drizzle-orm/bun-sqlite',
      'drizzle-orm/bun-sqlite/migrator',
      '@aws-sdk/client-sqs',
      '@modelcontextprotocol/sdk',
      '@guren/cli',
      'zod',
    ],
  },
])
