import { resolve } from 'node:path'
import { consola } from 'consola'
import {
  discoverControllerFiles,
  discoverResourceFiles,
  discoverEventFiles,
  discoverJobFiles,
  discoverMiddlewareFiles,
  discoverValidatorFiles,
  discoverPolicyFiles,
  classNameFromPath,
  fileExists,
  directoryExists,
  excludeBarrelFiles,
} from './discovery'
import { listModels } from './model-list'
import { writeFileSafe } from './utils'

export interface GuidelinesOptions {
  cwd?: string
  output?: string
}

export async function generateGuidelines(options: GuidelinesOptions = {}): Promise<string> {
  const cwd = resolve(options.cwd ?? process.cwd())
  const lines: string[] = []

  lines.push('# Project Guidelines (auto-generated)')
  lines.push('')
  lines.push('> Generated by `bunx guren guidelines`. Do not edit manually.')
  lines.push('')

  // Naming conventions
  lines.push('## Naming Conventions')
  const controllers = excludeBarrelFiles(await discoverControllerFiles(cwd)).map(classNameFromPath)
  if (controllers.length > 0) {
    const allSingular = controllers.every((c) => !c.endsWith('sController'))
    lines.push(`- Controllers: ${allSingular ? 'singular' : 'plural'} resource name (e.g., ${controllers[0]})`)
  }
  lines.push(`- Models: PascalCase, singular (e.g., Post, User)`)
  lines.push(`- Inertia pages: nested folders under resources/js/pages/ (e.g., Posts/Index.tsx)`)
  lines.push(`- Server-rendered content Views (Controller.view()): app/View/ with the @jsxImportSource @guren/core pragma — never under resources/js/pages/`)
  lines.push('')

  // Auth setup
  lines.push('## Authentication')
  const hasAuth = await directoryExists(resolve(cwd, 'app/Http/Controllers/Auth'))
  const models = await listModels({ appRoot: cwd })
  const authModel = models.find((m) => m.usesAuth)
  if (hasAuth && authModel) {
    lines.push(`- Auth is configured with ${authModel.className} model`)
    lines.push('- Session-based authentication (web guard)')
  } else if (hasAuth) {
    lines.push('- Auth controllers present but no AuthenticatableModel found')
  } else {
    lines.push('- No auth configured. Run: `bunx guren add auth`')
  }
  lines.push('')

  // Models & Relationships
  lines.push('## Models & Relationships')
  if (models.length > 0) {
    for (const model of models) {
      const rels = model.relationships.map((r) => {
        const target = r.relatedModel ? ` → ${r.relatedModel}` : ''
        return `${r.name} (${r.type}${target})`
      })
      const traits: string[] = []
      if (model.usesAuth) traits.push('Authenticatable')
      if (model.hasSoftDeletes) traits.push('SoftDeletes')
      const traitStr = traits.length > 0 ? ` [${traits.join(', ')}]` : ''

      lines.push(`- **${model.className}**${traitStr}: ${rels.length > 0 ? rels.join(', ') : 'no relationships'}`)
    }
  } else {
    lines.push('- No models found')
  }
  lines.push('')

  // Validation approach
  lines.push('## Validation')
  const validators = excludeBarrelFiles(await discoverValidatorFiles(cwd)).map(classNameFromPath)
  if (validators.length > 0) {
    lines.push(`- Centralized validators in app/Http/Validators/`)
    lines.push(`- Available: ${validators.join(', ')}`)
    lines.push('- Pattern: Zod schemas exported per resource')
  } else {
    lines.push('- No centralized validators found. Validation done inline in controllers.')
  }
  lines.push('')

  // Authorization
  lines.push('## Authorization')
  const policies = excludeBarrelFiles(await discoverPolicyFiles(cwd)).map(classNameFromPath)
  if (policies.length > 0) {
    lines.push('- Policies in app/Policies/ — enforce with `await this.authorize(ability, [Model, record])` in controllers')
    lines.push(`- Available: ${policies.join(', ')}`)
  } else {
    lines.push('- No policies found. Scaffold with `bunx guren make:policy <Model>` and register via `getGate().policy(Model, ModelPolicy)`')
  }
  lines.push('')

  // Security rules
  lines.push('## Security Rules (checked by `bunx guren audit`)')
  lines.push('- Validate every mutating route: call `this.validateBody(schema)` in controller actions (route `body` schemas are type-only for controllers; they are runtime-enforced only for inline handlers)')
  lines.push("- Protect mutating routes: wrap in `router.middleware('auth').group(...)` or call `this.auth.userOrFail()` (optional reads like `auth.user()` do not enforce)")
  lines.push('- Never interpolate values into raw SQL (`sql.raw`) — drizzle `sql` templates bind values safely')
  lines.push('- Never hardcode credentials — read secrets via `process.env`')
  lines.push('- Whitelist mass-assignable columns on every model — prefer the typed `defineModel(table, { fillable: [...] })` option (column typos become compile errors); `static fillable = [...]` also works')
  lines.push('')

  // Resources
  const resources = excludeBarrelFiles(await discoverResourceFiles(cwd)).map(classNameFromPath)
  if (resources.length > 0) {
    lines.push('## API Resources')
    lines.push(`- All API responses use JsonResource pattern`)
    lines.push(`- Available: ${resources.join(', ')}`)
    lines.push('')
  }

  // Events & Jobs
  const events = excludeBarrelFiles(await discoverEventFiles(cwd)).map(classNameFromPath)
  const jobs = excludeBarrelFiles(await discoverJobFiles(cwd)).map(classNameFromPath)
  const middleware = excludeBarrelFiles(await discoverMiddlewareFiles(cwd)).map(classNameFromPath)

  if (events.length > 0 || jobs.length > 0) {
    lines.push('## Events & Jobs')
    if (events.length > 0) lines.push(`- Events: ${events.join(', ')}`)
    if (jobs.length > 0) lines.push(`- Jobs: ${jobs.join(', ')}`)
    lines.push('')
  }

  if (middleware.length > 0) {
    lines.push('## Middleware')
    lines.push(`- Custom middleware: ${middleware.join(', ')}`)
    lines.push('')
  }

  // When creating new features
  lines.push('## When Creating New Features')
  lines.push('1. Create model in `app/Models/`')
  lines.push('2. Create controller in `app/Http/Controllers/`')
  lines.push('3. Create Inertia pages in `resources/js/pages/{Feature}/` (server-rendered content Views go in `app/View/`)')
  lines.push('4. Create validator in `app/Http/Validators/` (`bunx guren make:validator <Name> --fields "..."`)')
  lines.push('5. Create resource in `app/Http/Resources/`')
  lines.push('6. Register routes in `routes/web.ts`')
  lines.push('7. Run `bunx guren codegen` after adding routes')
  lines.push('8. Run `bunx guren audit` and fix any findings before opening a PR')
  lines.push('')

  const output = lines.join('\n')

  if (options.output) {
    await writeFileSafe(resolve(cwd, options.output), output, { force: true })
    consola.success(`Guidelines written to ${options.output}`)
  }

  return output
}
