/**
 * The prototype half of `make:feature` (RFC 0021 Part 3): the page-data type
 * the pages are built against, the fixture entries and seed appended to
 * `resources/js/prototype/index.ts`, and the promotion-time Resource typed
 * against that same type. Appending is anchored on the `state: () => ({` and
 * `routes: {` lines the `add prototype` template ships; a fixture rewritten
 * past those anchors gets the block printed for a manual paste instead.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { consola } from 'consola'
import { PROTOTYPE_FIXTURE_PATH } from './add-prototype'
import type { FieldDefinition, FieldType } from './fields'
import { insertImport } from './patch-helpers'
import { pagesAccessor } from './utils'

export interface PrototypeFeature {
  singular: string
  /** The `state()` key holding the seeded rows: the route variable (`blogPosts`), not the PascalCase collection. */
  collection: string
  routeName: string
  variableName: string
  fields: FieldDefinition[]
}

/** Where the page-data type lives: imported by the pages now and by the Resource after promotion. */
export function prototypeTypesPath(singular: string): string {
  return `resources/js/types/${singular}.ts`
}

export function prototypeTypesSpecifier(singular: string): string {
  return `@/resources/js/types/${singular}`
}

function tsFieldType(field: FieldDefinition): string {
  const map: Record<FieldType, string> = {
    string: 'string',
    text: 'string',
    number: 'number',
    boolean: 'boolean',
    date: 'string',
    json: 'Record<string, unknown>',
  }
  const base = map[field.type]
  return field.nullable ? `${base} | null` : base
}

export function generatePrototypeTypes(singular: string, fields: FieldDefinition[]): string {
  const lines = ['  id: number', ...fields.map((field) => `  ${field.name}: ${tsFieldType(field)}`)]
  return `/**
 * The ${singular} shape the prototype pages render. When the backend arrives,
 * ${singular}Resource serializes to this same type, so what the customer saw
 * is what the API delivers.
 */
export interface ${singular}Data extends Record<string, unknown> {
${lines.join('\n')}
}
`
}

function sampleValue(field: FieldDefinition, index: number): string {
  switch (field.type) {
    case 'number':
      return String(index * 10)
    case 'boolean':
      return index % 2 === 1 ? 'true' : 'false'
    case 'date':
      return `'2026-01-0${index}T09:00:00.000Z'`
    case 'json':
      return '{}'
    case 'text':
      return `'Longer sample text for ${field.name} ${index}.'`
    default:
      return `'Sample ${field.name} ${index}'`
  }
}

const SEED_COUNT = 3

/** `state()` additions: the seeded collection and the id counter the store entry increments. */
export function buildPrototypeSeed(feature: PrototypeFeature): string {
  const { singular, collection, fields } = feature
  const rows = Array.from({ length: SEED_COUNT }, (_, offset) => {
    const index = offset + 1
    const values = [`id: ${index}`, ...fields.map((field) => `${field.name}: ${sampleValue(field, index)}`)]
    return `      { ${values.join(', ')} },`
  })
  return [
    `    ${collection}: [`,
    ...rows,
    `    ] as ${singular}Data[],`,
    `    next${singular}Id: ${SEED_COUNT + 1},`,
  ].join('\n')
}

/** The seven entries `make:feature` registers, written against the handler context rather than standalone helpers. */
export function buildPrototypeEntries(feature: PrototypeFeature): string {
  const { singular, collection, routeName, variableName, fields } = feature
  const pages = pagesAccessor(routeName)
  // Field by field rather than `...body`: the validator leaves a nullable
  // field optional, and `undefined` is not the `null` the page-data type carries.
  const fromBody = fields.map((field) => `${field.name}: body.${field.name}${field.nullable ? ' ?? null' : ''}`).join(', ')
  return `    // ${singular}: generated by make:feature --prototype
    '${routeName}.index': ({ state, query, page }) =>
      page(${pages}.Index, paginate(state.${collection}, Number(query.page ?? 1), '/${routeName}')),
    '${routeName}.create': ({ page }) => page(${pages}.New, {}),
    '${routeName}.show': ({ state, params, page, notFound }) => {
      const ${variableName} = state.${collection}.find((item) => item.id === Number(params.id))
      return ${variableName} ? page(${pages}.Show, { ${variableName} }) : notFound()
    },
    '${routeName}.edit': ({ state, params, page, notFound }) => {
      const ${variableName} = state.${collection}.find((item) => item.id === Number(params.id))
      return ${variableName} ? page(${pages}.Edit, { ${variableName} }) : notFound()
    },
    '${routeName}.store': ({ state, body, redirect }) => {
      const ${variableName}: ${singular}Data = { id: state.next${singular}Id++, ${fromBody} }
      state.${collection}.unshift(${variableName})
      return redirect('${routeName}.show', { id: ${variableName}.id })
    },
    '${routeName}.update': ({ state, params, body, redirect, notFound }) => {
      const ${variableName} = state.${collection}.find((item) => item.id === Number(params.id))
      if (!${variableName}) return notFound()
      Object.assign(${variableName}, { ${fromBody} })
      return redirect('${routeName}.show', { id: ${variableName}.id })
    },
    '${routeName}.destroy': ({ state, params, redirect }) => {
      state.${collection} = state.${collection}.filter((item) => item.id !== Number(params.id))
      return redirect('${routeName}.index')
    },`
}

const STATE_ANCHOR = 'state: () => ({'
const ROUTES_ANCHOR = 'routes: {'

/**
 * Appends the seed and the entries to the fixture. Returns `'patched'`, or
 * `'manual'` after printing both blocks when an anchor is missing or the
 * feature is already present.
 */
export async function appendPrototypeEntries(cwd: string, feature: PrototypeFeature): Promise<'patched' | 'manual'> {
  const fixturePath = resolve(cwd, PROTOTYPE_FIXTURE_PATH)
  let content = await readFile(fixturePath, 'utf8')
  const seed = buildPrototypeSeed(feature)
  const entries = buildPrototypeEntries(feature)

  const stateIndex = content.indexOf(STATE_ANCHOR)
  const routesIndex = content.indexOf(ROUTES_ANCHOR)
  const alreadyThere = content.includes(`'${feature.routeName}.index':`)
  if (stateIndex === -1 || routesIndex === -1 || alreadyThere) {
    consola.warn(
      alreadyThere
        ? `${PROTOTYPE_FIXTURE_PATH} already answers '${feature.routeName}.index' — left unchanged. The generated blocks, for reference:`
        : `${PROTOTYPE_FIXTURE_PATH} has no \`${STATE_ANCHOR}\` / \`${ROUTES_ANCHOR}\` to append to. Add these by hand:`,
    )
    consola.log(`\n  // state()\n${seed}\n\n  // routes\n${entries}\n`)
    return 'manual'
  }

  // Routes first: its index is past the state anchor, so the state insertion
  // cannot move it.
  const routesAt = routesIndex + ROUTES_ANCHOR.length
  content = `${content.slice(0, routesAt)}\n${entries}${content.slice(routesAt)}`
  const stateAt = stateIndex + STATE_ANCHOR.length
  content = `${content.slice(0, stateAt)}\n${seed}${content.slice(stateAt)}`

  for (const statement of [
    `import type { ${feature.singular}Data } from '${prototypeTypesSpecifier(feature.singular)}'`,
    "import { pages } from '@/.guren/pages.gen'",
  ]) {
    content = insertImport(content, statement) ?? content
  }

  await writeFile(fixturePath, content, 'utf8')
  return 'patched'
}

/** The promotion-time Resource: `toArray()` answers the type the prototype pages were built on. */
export function generatePromotedResource(singular: string, fields: FieldDefinition[], fieldExpression: (field: FieldDefinition) => string): string {
  const toArrayFields = [
    '      id: this.resource.id,',
    ...fields.map((field) => `      ${field.name}: ${fieldExpression(field)},`),
  ].join('\n')

  return `import { Resource } from '@guren/core'
import type { ${singular}Record } from '../../Models/${singular}.js'
import type { ${singular}Data } from '${prototypeTypesSpecifier(singular)}'

/** The shape the prototype pages were built against, now the serializer's contract. */
export type ${singular}ResourceData = ${singular}Data

export class ${singular}Resource extends Resource<${singular}Record, ${singular}Data> {
  toArray(): ${singular}Data {
    return {
${toArrayFields}
    }
  }
}
`
}
