import { access, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import type { WriterOptions } from './utils'
import { ensureGitignoreEntry, ensureScaffoldFile } from './plugin-scaffold'

export const VERCEL_PLUGIN_PACKAGE = '@guren/plugin-vercel'

export async function installOfficialVercelPlugin(options: WriterOptions = {}): Promise<string[]> {
  await assertSupportedSsrApp()

  const updated: string[] = []

  if (await ensurePackageJsonScripts(options)) {
    updated.push('package.json')
  }

  if (await ensureGitignoreEntry('.vercel')) {
    updated.push('.gitignore')
  }

  if (await ensureScaffoldFile(
    'src/vercel.ts',
    vercelEntrypointTemplate(),
    options,
  )) {
    updated.push('src/vercel.ts')
  }

  if (await ensureScaffoldFile(
    'scripts/vercel-build.ts',
    vercelBuildTemplate(),
    options,
  )) {
    updated.push('scripts/vercel-build.ts')
  }

  if (await ensureScaffoldFile(
    'vercel.json',
    vercelConfigTemplate(),
    options,
  )) {
    updated.push('vercel.json')
  }

  return updated
}

export async function assertSupportedOfficialVercelPlugin(): Promise<void> {
  await assertSupportedSsrApp()
}

async function assertSupportedSsrApp(): Promise<void> {
  const requiredPaths = ['src/app.ts', 'resources/js/ssr.tsx']

  for (const path of requiredPaths) {
    try {
      await access(resolve(process.cwd(), path))
    } catch {
      throw new Error(
        `The official ${VERCEL_PLUGIN_PACKAGE} plugin currently supports SSR web apps only. Missing ${path}.`,
      )
    }
  }

  const packageJsonPath = resolve(process.cwd(), 'package.json')
  const rawPackage = await readFile(packageJsonPath, 'utf8')
  const packageJson = JSON.parse(rawPackage) as { scripts?: Record<string, string> }
  const buildScript = packageJson.scripts?.build ?? ''

  if (!buildScript.includes('--ssr')) {
    throw new Error(
      `The official ${VERCEL_PLUGIN_PACKAGE} plugin currently supports SSR web apps only. Expected package.json scripts.build to include --ssr.`,
    )
  }
}

async function ensurePackageJsonScripts(options: WriterOptions): Promise<boolean> {
  const packageJsonPath = resolve(process.cwd(), 'package.json')
  const rawPackage = await readFile(packageJsonPath, 'utf8')
  const packageJson = JSON.parse(rawPackage) as {
    scripts?: Record<string, string>
  }

  packageJson.scripts ??= {}

  let changed = false

  if (packageJson.scripts['vercel:build'] !== 'bun scripts/vercel-build.ts') {
    if (packageJson.scripts['vercel:build'] && !options.force) {
      return false
    }

    packageJson.scripts['vercel:build'] = 'bun scripts/vercel-build.ts'
    changed = true
  }

  if (!changed) {
    return false
  }

  await writeFile(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`, 'utf8')
  return true
}

function vercelEntrypointTemplate(): string {
  return `/**
 * Vercel Serverless Function entrypoint.
 *
 * Generated by \`bunx guren plugin ${VERCEL_PLUGIN_PACKAGE}\`.
 */
import app from './app.js'
import { createVercelHandler } from '${VERCEL_PLUGIN_PACKAGE}'

export default await createVercelHandler(app)
`
}

function vercelBuildTemplate(): string {
  return `/**
 * Assemble Vercel Build Output API structure.
 *
 * Generated by \`bunx guren plugin ${VERCEL_PLUGIN_PACKAGE}\`.
 */
import { buildVercelOutput } from '${VERCEL_PLUGIN_PACKAGE}'

buildVercelOutput({
  rootDir: new URL('..', import.meta.url),
  entrypoint: new URL('../src/vercel.ts', import.meta.url),
})
`
}

function vercelConfigTemplate(): string {
  return `${JSON.stringify({
    $schema: 'https://openapi.vercel.sh/vercel.json',
    bunVersion: '1.x',
    buildCommand: 'bun run build && bun run vercel:build',
    installCommand: 'bun install',
    outputDirectory: '.vercel/output',
    rewrites: [
      { source: '/public/(.*)', destination: '/$1' },
    ],
  }, null, 2)}
`
}
