import type { WriterOptions } from './utils'
import { ensureGitignoreEntry, ensureScaffoldFile } from './plugin-scaffold'

export const LAMBDA_PLUGIN_PACKAGE = '@guren/plugin-lambda'

export async function installOfficialLambdaPlugin(options: WriterOptions = {}): Promise<string[]> {
  const updated: string[] = []

  if (await ensureGitignoreEntry('.lambda')) {
    updated.push('.gitignore')
  }

  if (await ensureScaffoldFile('src/lambda.ts', lambdaEntrypointTemplate(), options)) {
    updated.push('src/lambda.ts')
  }

  return updated
}

function lambdaEntrypointTemplate(): string {
  return `/**
 * AWS Lambda entrypoints.
 *
 * Generated by \`bunx guren plugin ${LAMBDA_PLUGIN_PACKAGE}\`.
 * \`guren lambda:build\` bundles this module; each export becomes a Lambda
 * handler (e.g. \`handler.http\`).
 */
import app from './app.js'
import { createLambdaHandler, createSqsHandler } from '@guren/core/lambda'

// Boots once at cold start; every handler shares the booted application.
await app.boot()

// HTTP requests via API Gateway, ALB, or a Lambda Function URL.
export const http = createLambdaHandler(app)

// SQS queue job processing (wire an SQS event source to this handler).
export const queue = createSqsHandler()

// EventBridge scheduled tasks — export once your app defines a scheduler:
// import { createScheduleHandler } from '@guren/core/lambda'
// import { scheduler } from './scheduler.js'
// export const schedule = createScheduleHandler(scheduler)

// Console commands (migrations, seeders) — export once you have a kernel:
// import { createConsoleHandler } from '@guren/core/lambda'
// import { kernel } from './console.js'
// const consoleHandler = createConsoleHandler(kernel)
// export { consoleHandler as console }
`
}
