import type { WriterOptions } from './utils'
import { ensureGitignoreEntry, ensureScaffoldFile } from './plugin-scaffold'

export const LAMBDA_PLUGIN_PACKAGE = '@guren/plugin-lambda'

export async function installOfficialLambdaPlugin(options: WriterOptions = {}): Promise<string[]> {
  const updated: string[] = []

  if (await ensureGitignoreEntry('.lambda')) {
    updated.push('.gitignore')
  }

  // The entrypoint's console handler imports src/console.ts, which projects
  // created before that file existed do not have. Scaffold it here so
  // uncommenting the console export can't fail to resolve; apps that already
  // have one keep it untouched.
  if (await ensureScaffoldFile('src/console.ts', consoleKernelTemplate(), options)) {
    updated.push('src/console.ts')
  }

  if (await ensureScaffoldFile('src/lambda.ts', lambdaEntrypointTemplate(), options)) {
    updated.push('src/lambda.ts')
  }

  return updated
}

// Kept identical to packages/create-app/templates/{default,api-only}/src/console.ts —
// see packages/cli/tests/plugin.test.ts, which pins this to that file so the two
// can't drift the way they did when #223 rewrote the templates without this one.
function consoleKernelTemplate(): string {
  return `import { ConsoleKernel } from '@guren/core'
import app from './app.js'

export const kernel = new ConsoleKernel({ container: app.container })

// \`bunx guren make:command\` adds the import and the array entry for you; the
// empty array literal is what it edits, so keep it even while unused.
// \`bunx guren check\` warns about any command class this file never registers.
kernel.registerMany([])
`
}

function lambdaEntrypointTemplate(): string {
  return `/**
 * AWS Lambda entrypoints.
 *
 * Generated by \`bunx guren plugin ${LAMBDA_PLUGIN_PACKAGE}\`.
 * \`guren lambda:build\` bundles this module; each export becomes a Lambda
 * handler (e.g. \`handler.http\`).
 */
import app from './app.js'
import { createLambdaHandler, createSqsHandler } from '@guren/core/lambda'

// Boots once at cold start; every handler shares the booted application.
await app.boot()

// HTTP requests via API Gateway, ALB, or a Lambda Function URL.
export const http = createLambdaHandler(app)

// SQS queue job processing (wire an SQS event source to this handler).
export const queue = createSqsHandler()

// EventBridge scheduled tasks — export once your app defines a scheduler:
// import { createScheduleHandler } from '@guren/core/lambda'
// import { scheduler } from './scheduler.js'
// export const schedule = createScheduleHandler(scheduler)

// Console commands — uncomment to run them with \`aws lambda invoke\`, under
// the same names as \`bun run console\`.
// Writing and registering commands: https://guren.dev/docs/guides/console
// Seeders can't run in the bundle — use \`bunx guren db:seed --force\` instead.
// import { createConsoleHandler } from '@guren/core/lambda'
// import { kernel } from './console.js'
//
// const consoleHandler = createConsoleHandler(kernel)
// export { consoleHandler as console }
`
}
