import { resolve } from 'node:path'
import { mkdir, writeFile } from 'node:fs/promises'
import { consola } from 'consola'

/** One generated spec view. */
export interface SpecArtifact {
  /** File name inside `docs/spec/`, e.g. `er.md`. */
  fileName: string
  /** Full file content, banner included, with a trailing newline. */
  content: string
}

export const SPEC_DIR = 'docs/spec'

/**
 * Every artifact starts with this banner. Content must be deterministic —
 * stable sort order, no timestamps, no absolute paths — so regenerating
 * with no code change is byte-identical (what makes `check --spec` diffs
 * and PR reviews meaningful).
 */
export const SPEC_BANNER =
  '<!-- Generated by `bunx guren spec:generate` — do not edit by hand. -->'

/**
 * Code-unit string comparison for spec ordering. `localeCompare` depends
 * on the runtime's ICU build, which would make `check --spec` diff a dev
 * machine against CI; code-unit order is identical everywhere.
 */
export function compareStrings(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0
}

export interface SpecGenerateOptions {
  cwd?: string
  routesFile?: string
}

/**
 * All four spec views, in memory. `check --spec` diffs these against the
 * committed files; `spec:generate` writes them.
 */
export async function generateSpecArtifacts(
  options: SpecGenerateOptions = {},
): Promise<SpecArtifact[]> {
  const cwd = resolve(options.cwd ?? process.cwd())

  // Deferred imports keep the four generators independently testable and
  // avoid loading route/page tooling for callers that never generate.
  const [{ generateErSpec }, { generateDomainSpec }, { generateScreensSpec }, { generateModulesSpec }] =
    await Promise.all([
      import('./spec-er'),
      import('./spec-domain'),
      import('./spec-screens'),
      import('./spec-modules'),
    ])

  return Promise.all([
    generateErSpec(cwd),
    generateDomainSpec(cwd),
    generateScreensSpec(cwd, options.routesFile),
    generateModulesSpec(cwd),
  ])
}

export async function writeSpecArtifacts(options: SpecGenerateOptions = {}): Promise<string[]> {
  const cwd = resolve(options.cwd ?? process.cwd())
  const artifacts = await generateSpecArtifacts(options)

  const dir = resolve(cwd, SPEC_DIR)
  await mkdir(dir, { recursive: true })

  const written: string[] = []
  for (const artifact of artifacts) {
    const path = resolve(dir, artifact.fileName)
    await writeFile(path, artifact.content, 'utf-8')
    written.push(`${SPEC_DIR}/${artifact.fileName}`)
    consola.success(`Spec view generated at ${SPEC_DIR}/${artifact.fileName}`)
  }
  return written
}
