/**
 * Leaf module for the spec-view contract — imported by every generator and
 * by the orchestrator, so it must not import any of them.
 */

/** One generated spec view. */
export interface SpecArtifact {
  /** File name inside `docs/spec/`, e.g. `er.md`. */
  fileName: string
  /** Full file content, banner included, with a trailing newline. */
  content: string
  /**
   * Set when the generator had to degrade (e.g. the route graph failed to
   * import). A degraded artifact must never be written or byte-compared —
   * it would replace real content with a hollow document that then reads
   * as "in sync". The value explains why, for the warn message.
   */
  degraded?: string
}

export const SPEC_DIR = 'docs/spec'

/**
 * Every artifact starts with this banner. Content must be deterministic —
 * stable sort order, no timestamps, no absolute paths — so regenerating
 * with no code change is byte-identical (what makes `check --spec` diffs
 * and PR reviews meaningful).
 */
export const SPEC_BANNER =
  '<!-- Generated by `bunx guren spec:generate` — do not edit by hand. -->'

/**
 * OKF frontmatter lines for a generated spec view. `type` is the one
 * field OKF requires; `generated.by` marks the view machine-written in
 * the actor convention. No `generated.at` — content must stay
 * deterministic (see SPEC_BANNER), and git history already carries the
 * date.
 */
export function specFrontmatter(title: string, description: string): string[] {
  return [
    '---',
    'type: spec',
    `title: ${title}`,
    `description: ${description}`,
    'generated: { by: process:guren-spec-generate }',
    '---',
    '',
  ]
}

/**
 * Code-unit string comparison for spec ordering. `localeCompare` depends
 * on the runtime's ICU build, which would make `check --spec` diff a dev
 * machine against CI; code-unit order is identical everywhere.
 */
export function compareStrings(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0
}

/**
 * A Mermaid-safe token: identifiers interpolated into `erDiagram` and
 * `classDiagram` bodies must stay alphanumeric/underscore (schema keys can
 * be quoted strings with spaces; class names can legally contain `$`).
 * Guarantees a leading letter so ER attribute types stay valid.
 */
export function mermaidToken(value: string): string {
  const token = value.replace(/[^A-Za-z0-9_]/g, '_')
  return /^[A-Za-z]/.test(token) ? token : `x${token}`
}
