/** Leaf module for the spec-view contract: imported by every generator, importing none. */

/** One generated spec view. */
export interface SpecArtifact {
  /** File name inside `docs/spec/`, e.g. `er.md`. */
  fileName: string
  /** Full file content, banner included, with a trailing newline. */
  content: string
  /**
   * Set when the generator had to degrade (the route graph failed to import, say). Never
   * write or byte-compare one: it would replace real content with a hollow document that
   * then reads as "in sync". The value explains why, for the warn message.
   */
  degraded?: string
}

export const SPEC_DIR = 'docs/spec'

/**
 * Every artifact starts with this banner. Content must be deterministic — stable sort
 * order, no timestamps, no absolute paths — so regenerating with no code change is
 * byte-identical, which is what `check --spec` compares.
 */
export const SPEC_BANNER =
  '<!-- Generated by `bunx guren spec:generate` — do not edit by hand. -->'

/**
 * The opening lines every generated spec view shares: OKF frontmatter, the do-not-edit
 * banner, and the H1. No `generated.at` — content must stay deterministic (see
 * SPEC_BANNER). Frontmatter has to lead the file or `parseDocFrontmatter` never sees it.
 */
export function specHeader(title: string, description: string): string[] {
  return [
    '---',
    'type: spec',
    `title: ${title}`,
    `description: ${description}`,
    'generated: { by: process:guren-spec-generate }',
    '---',
    '',
    SPEC_BANNER,
    '',
    `# ${title}`,
    '',
  ]
}

/**
 * Code-unit string comparison for spec ordering. `localeCompare` depends on the runtime's
 * ICU build, which would make `check --spec` diff a dev machine against CI.
 */
export function compareStrings(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0
}

/**
 * A Mermaid-safe token: identifiers in `erDiagram`/`classDiagram` bodies must stay
 * alphanumeric/underscore, with a leading letter so ER attribute types stay valid.
 */
export function mermaidToken(value: string): string {
  const token = value.replace(/[^A-Za-z0-9_]/g, '_')
  return /^[A-Za-z]/.test(token) ? token : `x${token}`
}
