import { serveStatic } from 'hono/bun'
import { dirname, resolve, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Application } from './Application'
import {
  createStaticRewrite,
  registerDevAssets,
  resolveInertiaClientDir,
  resolveInertiaClientRoute,
  type DevAssetsOptions,
} from './dev-assets'
import { registerRootPublicAssets } from './public-assets'
import { isPathWithin, isRealPathWithin } from '../support/contained-path'
import { parseImportMap } from '../support/import-map'
import { DEFAULT_DEV_STYLES_ENTRY } from '../support/inertia-defaults'
import { trimTrailingSlashes } from '../support/trim-slashes'
import { hash } from '../encryption/Hash'
import { loadViteManifest, getManifestFile, getManifestCss, type ViteManifest } from './vite-manifest'

export interface InertiaAssetsOptions extends DevAssetsOptions {
  /** Default stylesheet entry embedded into Inertia responses. */
  stylesEntry?: string
  /** Default script entry embedded into Inertia responses (production). */
  scriptEntry?: string
  /** Path to the SSR bundle entry consumed by the Inertia engine. */
  ssrEntry?: string
  /** Path to the SSR manifest file generated by the build. */
  ssrManifest?: string
}

export interface AutoConfigureInertiaOptions extends InertiaAssetsOptions {
  /** Dev server URL used when NODE_ENV !== 'production'. */
  devServerUrl?: string
  /** Output directory for Vite SSR bundles (relative to project root). */
  ssrOutDir?: string
  /** Enables SSR auto-wiring (defaults to true). */
  enableSsr?: boolean
}

const DEFAULT_STYLES_ENTRY = '/public/assets/app.css'
const DEFAULT_SCRIPT_ENTRY = '/assets/app.js'
const DEFAULT_VENDOR_CLIENT_PATH = '/vendor/inertia-client.tsx'

export function configureInertiaAssets(app: Application, options: InertiaAssetsOptions): void {
  const stylesEntry = options.stylesEntry ?? DEFAULT_STYLES_ENTRY
  process.env.GUREN_INERTIA_STYLES = process.env.GUREN_INERTIA_STYLES ?? stylesEntry
  const providedSsrEntry = options.ssrEntry
  const providedSsrManifest = options.ssrManifest

  const isProduction = process.env.NODE_ENV === 'production'

  if (!isProduction) {
    const devSsrEntry = resolveDevSsrEntry(options)

    if (!process.env.GUREN_INERTIA_SSR_ENTRY && devSsrEntry) {
      process.env.GUREN_INERTIA_SSR_ENTRY = devSsrEntry
    }

    if (!process.env.GUREN_INERTIA_SSR_MANIFEST) {
      process.env.GUREN_INERTIA_SSR_MANIFEST = providedSsrManifest ?? ''
    }

    registerDevAssets(app, options)
    return
  }

  const scriptEntry = options.scriptEntry ?? DEFAULT_SCRIPT_ENTRY
  process.env.GUREN_INERTIA_ENTRY = process.env.GUREN_INERTIA_ENTRY ?? scriptEntry

  if (!process.env.GUREN_INERTIA_SSR_ENTRY && providedSsrEntry) {
    process.env.GUREN_INERTIA_SSR_ENTRY = providedSsrEntry
  }

  if (!process.env.GUREN_INERTIA_SSR_MANIFEST && providedSsrManifest) {
    process.env.GUREN_INERTIA_SSR_MANIFEST = providedSsrManifest
  }

  const moduleDir = options.importMeta ? dirname(fileURLToPath(options.importMeta.url)) : undefined
  const publicPathOption = options.publicPath === undefined ? '../public' : options.publicPath
  const publicDir = options.publicDir ?? (moduleDir && publicPathOption ? resolve(moduleDir, publicPathOption) : undefined)

  if (!publicDir || publicPathOption === false) {
    return
  }

  const publicRoute = options.publicRoute ?? '/public/*'
  const rewriteRequestPath = createStaticRewrite(publicRoute)
  const hashedAssetsPrefix = `${publicRouteBase(publicRoute)}/assets/`

  app.use(
    publicRoute,
    serveStatic({
      root: publicDir,
      rewriteRequestPath,
      // Vite writes content-hashed filenames under `assets/`, so those
      // responses can be cached forever. Files elsewhere in public/ keep
      // stable names and must stay revalidatable.
      onFound: (_path, ctx) => {
        if (ctx.req.path.startsWith(hashedAssetsPrefix)) {
          ctx.header('Cache-Control', 'public, max-age=31536000, immutable')
        }
      },
    }),
  )

  if (options.favicon !== false) {
    app.hono.get('/favicon.ico', () => new Response(null, { status: 204 }))
  }

  registerRootPublicAssets(app, publicDir, options.rootPublicAssets)

  if (options.inertiaClient !== false) {
    try {
      registerBuiltInertiaClient(
        app,
        resolveInertiaClientDir(),
        options.inertiaClientPath ?? DEFAULT_VENDOR_CLIENT_PATH,
      )
    } catch (error) {
      console.warn('Unable to resolve @guren/inertia-client for production serving.', error)
    }
  }
}

/** The route base ahead of the wildcard, as {@link createStaticRewrite} sees it. */
function publicRouteBase(route: string): string {
  const wildcardIndex = route.indexOf('*')
  const base = wildcardIndex >= 0 ? route.slice(0, wildcardIndex) : route
  return trimTrailingSlashes(base)
}

/**
 * Serves the built Inertia client and the chunks it imports out of the
 * resolved package directory.
 *
 * Split out of {@link configureInertiaAssets} so it can be pointed at a
 * directory: the caller derives `inertiaClientDir` from `import.meta.resolve`,
 * which no test can redirect at a fixture.
 */
export function registerBuiltInertiaClient(
  app: Application,
  inertiaClientDir: string,
  inertiaClientPath: string,
): void {
  const {
    base: inertiaClientBase,
    pattern: inertiaClientPattern,
    requestPath: inertiaClientRequestPath,
  } = resolveInertiaClientRoute(inertiaClientPath)

  app.hono.get(inertiaClientPattern, async (ctx) => {
    const relativeRequest = ctx.req.path.slice(inertiaClientBase.length) || inertiaClientRequestPath

    let targetPath: string
    // Stays undefined for the entry: it is configuration-derived rather than
    // request-derived, and a package layout may well have it symlinked out of
    // `inertiaClientDir`.
    let containmentRoot: string | undefined

    if (relativeRequest === inertiaClientRequestPath) {
      targetPath = join(inertiaClientDir, 'app.js')
    } else {
      targetPath = resolve(inertiaClientDir, relativeRequest)
      containmentRoot = inertiaClientDir

      if (!isPathWithin(containmentRoot, targetPath)) {
        return ctx.notFound()
      }
    }

    const file = Bun.file(targetPath)

    if (!(await file.exists())) {
      return ctx.notFound()
    }

    // Canonicalized only now: `realpath` needs a path that exists.
    if (containmentRoot && !(await isRealPathWithin(containmentRoot, targetPath))) {
      return ctx.notFound()
    }

    const contentType = file.type || 'application/javascript; charset=utf-8'

    return new Response(file, {
      headers: {
        'Content-Type': contentType,
        'Cache-Control': 'public, max-age=31536000',
      },
    })
  })
}

export function autoConfigureInertiaAssets(app: Application, options: AutoConfigureInertiaOptions): void {
  const providedEnv = captureInertiaEnvFlags()
  configureInertiaAssets(app, options)

  const moduleDir = options.importMeta ? dirname(fileURLToPath(options.importMeta.url)) : undefined
  const resourcesDir = resolveResourcesDir(options, moduleDir)
  const ssrOutDir = options.ssrOutDir ?? '.guren/ssr'
  const importMapEntries = parseImportMap(process.env.GUREN_INERTIA_IMPORT_MAP, {
    context: 'GUREN_INERTIA_IMPORT_MAP from environment',
  })
  const ssrEnabled = options.enableSsr ?? true
  const setEnvIfUserDidNotProvide = (key: InertiaEnvKey, value: string) => {
    if (providedEnv[key]) {
      return
    }

    process.env[key] = value
  }

  if (!moduleDir) {
    return
  }

  const isProduction =
    (process.env.NODE_ENV ?? 'development') === 'production' && typeof process.env.VITE_DEV_SERVER_URL !== 'string'

  if (!isProduction) {
    const devServerUrl = options.devServerUrl ?? process.env.VITE_DEV_SERVER_URL ?? 'http://localhost:5173'
    const normalizedDevServerUrl = normalizeDevServerUrl(devServerUrl)
    setEnvIfUserDidNotProvide('GUREN_INERTIA_ENTRY', `${normalizedDevServerUrl}/resources/js/dev-entry.ts`)
    setEnvIfUserDidNotProvide('GUREN_INERTIA_STYLES', options.stylesEntry ?? DEFAULT_DEV_STYLES_ENTRY)
    importMapEntries['@guren/inertia-client'] = DEFAULT_VENDOR_CLIENT_PATH

    if (ssrEnabled) {
      const ssrEntryPath = options.ssrEntry ?? (resourcesDir ? resolve(resourcesDir, 'js/ssr.tsx') : undefined)

      if (ssrEntryPath) {
        setEnvIfUserDidNotProvide('GUREN_INERTIA_SSR_ENTRY', ssrEntryPath)
      }

      setEnvIfUserDidNotProvide('GUREN_INERTIA_SSR_MANIFEST', '')
    } else {
      setEnvIfUserDidNotProvide('GUREN_INERTIA_SSR_ENTRY', '')
      setEnvIfUserDidNotProvide('GUREN_INERTIA_SSR_MANIFEST', '')
    }

    process.env.GUREN_INERTIA_IMPORT_MAP = JSON.stringify(importMapEntries)
    return
  }

  const clientManifest = loadViteManifest(
    [
      resolve(moduleDir, '../public/assets/manifest.json'),
      resolve(moduleDir, '../public/assets/.vite/manifest.json'),
    ],
    'client',
  )

  const clientEntry = clientManifest?.['resources/js/app.tsx']
  const clientEntryFile = getManifestFile(clientEntry)
  const clientCssFiles = getManifestCss(clientEntry)

  if (clientManifest?.__raw__) {
    setEnvIfUserDidNotProvide(
      'GUREN_INERTIA_VERSION',
      hash(clientManifest.__raw__, 'sha1').slice(0, 12),
    )
  }

  if (clientEntryFile) {
    setEnvIfUserDidNotProvide('GUREN_INERTIA_ENTRY', `/public/assets/${clientEntryFile.replace(/^\//u, '')}`)
  }

  if (clientCssFiles?.length) {
    setEnvIfUserDidNotProvide(
      'GUREN_INERTIA_STYLES',
      clientCssFiles.map((href) => `/public/assets/${href.replace(/^\//u, '')}`).join(','),
    )
  }

  importMapEntries['@guren/inertia-client'] = DEFAULT_VENDOR_CLIENT_PATH

  if (!ssrEnabled) {
    if (Object.keys(importMapEntries).length > 0) {
      process.env.GUREN_INERTIA_IMPORT_MAP = JSON.stringify(importMapEntries)
    }

    setEnvIfUserDidNotProvide('GUREN_INERTIA_SSR_ENTRY', '')
    setEnvIfUserDidNotProvide('GUREN_INERTIA_SSR_MANIFEST', '')
    return
  }

  const ssrManifestPaths = [
    options.ssrManifest,
    resolve(moduleDir, `../${ssrOutDir}/manifest.json`),
    resolve(moduleDir, `../${ssrOutDir}/.vite/manifest.json`),
    resolve(moduleDir, `../${ssrOutDir}/ssr-manifest.json`),
    resolve(moduleDir, '../build/ssr/manifest.json'),
    resolve(moduleDir, '../build/ssr/.vite/manifest.json'),
    resolve(moduleDir, '../build/ssr/ssr-manifest.json'),
    resolve(moduleDir, '../public/assets/.ssr/manifest.json'),
    resolve(moduleDir, '../public/assets/.ssr/.vite/manifest.json'),
    resolve(moduleDir, '../public/assets/.ssr/ssr-manifest.json'),
    resolve(moduleDir, '../public/assets/.vite/ssr-manifest.json'),
  ].filter((value): value is string => Boolean(value))

  const ssrManifest = loadViteManifest(ssrManifestPaths, 'SSR')

  const ssrEntry = ssrManifest?.['resources/js/ssr.tsx']
  const ssrEntryFile = getManifestFile(ssrEntry)
  const ssrEntryRoot = deriveAssetRoot(ssrManifest, resolve(moduleDir, `../${ssrOutDir}`))

  if (ssrEntryFile && ssrEntryRoot) {
    setEnvIfUserDidNotProvide(
      'GUREN_INERTIA_SSR_ENTRY',
      resolve(ssrEntryRoot, ssrEntryFile.replace(/^\//u, '')),
    )
  }

  if (Object.keys(importMapEntries).length > 0) {
    process.env.GUREN_INERTIA_IMPORT_MAP = JSON.stringify(importMapEntries)
  }

  if (ssrManifest?.__path__) {
    setEnvIfUserDidNotProvide('GUREN_INERTIA_SSR_MANIFEST', ssrManifest.__path__)
  }
}

type InertiaEnvKey =
  | 'GUREN_INERTIA_ENTRY'
  | 'GUREN_INERTIA_STYLES'
  | 'GUREN_INERTIA_SSR_ENTRY'
  | 'GUREN_INERTIA_SSR_MANIFEST'
  | 'GUREN_INERTIA_VERSION'

function captureInertiaEnvFlags(): Record<InertiaEnvKey, boolean> {
  return {
    GUREN_INERTIA_ENTRY: process.env.GUREN_INERTIA_ENTRY !== undefined,
    GUREN_INERTIA_STYLES: process.env.GUREN_INERTIA_STYLES !== undefined,
    GUREN_INERTIA_SSR_ENTRY: process.env.GUREN_INERTIA_SSR_ENTRY !== undefined,
    GUREN_INERTIA_SSR_MANIFEST: process.env.GUREN_INERTIA_SSR_MANIFEST !== undefined,
    GUREN_INERTIA_VERSION: process.env.GUREN_INERTIA_VERSION !== undefined,
  }
}

function resolveDevSsrEntry(options: InertiaAssetsOptions): string | undefined {
  if (options.ssrEntry) {
    return options.ssrEntry
  }

  if (options.resourcesDir) {
    return resolve(options.resourcesDir, 'js/ssr.tsx')
  }

  const moduleDir = options.importMeta ? dirname(fileURLToPath(options.importMeta.url)) : undefined

  if (!moduleDir) {
    return undefined
  }

  const resourcesPath = options.resourcesPath ?? '../resources'
  const resourcesDir = resolve(moduleDir, resourcesPath)

  return resolve(resourcesDir, 'js/ssr.tsx')
}

function normalizeDevServerUrl(value: string): string {
  if (!value) {
    return value
  }

  const trimmed = value.trim()
  if (!trimmed) {
    return trimmed
  }

  const stripped = trimTrailingSlashes(trimmed)
  return stripped.length > 0 ? stripped : '/'
}


function deriveAssetRoot(manifest: ViteManifest | undefined, fallback: string): string | undefined {
  if (!manifest?.__path__) {
    return fallback
  }

  return resolve(dirname(manifest.__path__), '..')
}

function resolveResourcesDir(options: InertiaAssetsOptions, moduleDir?: string): string | undefined {
  if (options.resourcesDir) {
    return options.resourcesDir
  }

  if (!moduleDir) {
    return undefined
  }

  const resourcesPath = options.resourcesPath ?? '../resources'
  return resolve(moduleDir, resourcesPath)
}
