import { serveStatic } from 'hono/bun'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Application } from './Application'
import { createStaticRewrite, registerDevAssets, type DevAssetsOptions } from './dev-assets'

export interface InertiaAssetsOptions extends DevAssetsOptions {
  /** Default stylesheet entry embedded into Inertia responses. */
  stylesEntry?: string
  /** Default script entry embedded into Inertia responses (production). */
  scriptEntry?: string
  /** Path to the SSR bundle entry consumed by the Inertia engine. */
  ssrEntry?: string
  /** Path to the SSR manifest file generated by the build. */
  ssrManifest?: string
}

const DEFAULT_STYLES_ENTRY = '/public/assets/app.css'
const DEFAULT_SCRIPT_ENTRY = '/assets/app.js'

export function configureInertiaAssets(app: Application, options: InertiaAssetsOptions): void {
  const stylesEntry = options.stylesEntry ?? DEFAULT_STYLES_ENTRY
  process.env.GUREN_INERTIA_STYLES = process.env.GUREN_INERTIA_STYLES ?? stylesEntry
  const providedSsrEntry = options.ssrEntry
  const providedSsrManifest = options.ssrManifest

  const isProduction = process.env.NODE_ENV === 'production'

  if (!isProduction) {
    const devSsrEntry = resolveDevSsrEntry(options)

    if (!process.env.GUREN_INERTIA_SSR_ENTRY && devSsrEntry) {
      process.env.GUREN_INERTIA_SSR_ENTRY = devSsrEntry
    }

    if (!process.env.GUREN_INERTIA_SSR_MANIFEST) {
      process.env.GUREN_INERTIA_SSR_MANIFEST = providedSsrManifest ?? ''
    }

    registerDevAssets(app, options)
    return
  }

  const scriptEntry = options.scriptEntry ?? DEFAULT_SCRIPT_ENTRY
  process.env.GUREN_INERTIA_ENTRY = process.env.GUREN_INERTIA_ENTRY ?? scriptEntry

  if (!process.env.GUREN_INERTIA_SSR_ENTRY && providedSsrEntry) {
    process.env.GUREN_INERTIA_SSR_ENTRY = providedSsrEntry
  }

  if (!process.env.GUREN_INERTIA_SSR_MANIFEST && providedSsrManifest) {
    process.env.GUREN_INERTIA_SSR_MANIFEST = providedSsrManifest
  }

  const moduleDir = options.importMeta ? dirname(fileURLToPath(options.importMeta.url)) : undefined
  const publicPathOption = options.publicPath === undefined ? '../public' : options.publicPath
  const publicDir = options.publicDir ?? (moduleDir && publicPathOption ? resolve(moduleDir, publicPathOption) : undefined)

  if (!publicDir || publicPathOption === false) {
    return
  }

  const publicRoute = options.publicRoute ?? '/public/*'
  const rewriteRequestPath = createStaticRewrite(publicRoute)

  app.use(
    publicRoute,
    serveStatic({
      root: publicDir,
      rewriteRequestPath,
    }),
  )

  if (options.favicon !== false) {
    app.hono.get('/favicon.ico', () => new Response(null, { status: 204 }))
  }
}

function resolveDevSsrEntry(options: InertiaAssetsOptions): string | undefined {
  if (options.ssrEntry) {
    return options.ssrEntry
  }

  if (options.resourcesDir) {
    return resolve(options.resourcesDir, 'js/ssr.tsx')
  }

  const moduleDir = options.importMeta ? dirname(fileURLToPath(options.importMeta.url)) : undefined

  if (!moduleDir) {
    return undefined
  }

  const resourcesPath = options.resourcesPath ?? '../resources'
  const resourcesDir = resolve(moduleDir, resourcesPath)

  return resolve(resourcesDir, 'js/ssr.tsx')
}
