/**
 * The Worker bindings this app expects, hand-written rather than generated by
 * `wrangler types`: `Env` is named by `app/Agents/Triager.ts`, which the Bun
 * test run and `tsc` both read, and neither can depend on a wrangler invocation
 * having happened first.
 */
export interface Env {
  /** The D1 database `wrangler.jsonc` binds; `unknown` because only the ORM reads it. */
  DB: unknown
  /** The `Triager` Durable Object namespace, absent under Bun. */
  TRIAGER?: {
    idFromName(name: string): unknown
    get(id: unknown): TriagerStub
  }
}

/** The public RPC surface `app/Agents/Triager.ts` exposes over the binding. */
export interface TriagerStub {
  sweep(): Promise<unknown>
  report(): Promise<unknown>
}
